name = "affinityx"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"
watch_dir = "."

[env.production]
name = "affinityx-production"

[env.staging]
name = "affinityx-staging"

[[env.production.rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.ts", "**/*.tsx"]

[[env.staging.rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.ts", "**/*.tsx"] 